[colors]
[colors.primary]
background = "#303446"
foreground = "#b5bfe2"

[colors.normal]
black   = "#303446"
red     = "#e78284"
green   = "#a6d189"
yellow  = "#e5c890"
blue    = "#8caaee"
magenta = "#ca9ee6"
cyan    = "#81c8be"
white   = "#c6d0f5"

[colors.bright]
black   = "#51576d"
red     = "#e78284"
green   = "#a6d189"
yellow  = "#e5c890"
blue    = "#8caaee"
magenta = "#ca9ee6"
cyan    = "#81c8be"
white   = "#b5bfe2"

[colors.cursor]
text   = "#303446"
cursor = "#b5bfe2"
