accent = "#8caaee"
cursor = "#b5bfe2"
foreground = "#b5bfe2"
background = "#303446"
selection_foreground = "#303446"
selection_background = "#f4b8e4"

color0 = "#303446"
color1 = "#e78284"
color2 = "#a6d189"
color3 = "#e5c890"
color4 = "#8caaee"
color5 = "#ca9ee6"
color6 = "#81c8be"
color7 = "#c6d0f5"
color8 = "#51576d"
color9 = "#e78284"
color10 = "#a6d189"
color11 = "#e5c890"
color12 = "#8caaee"
color13 = "#ca9ee6"
color14 = "#81c8be"
color15 = "#b5bfe2"
